### PR TITLE
decoupling of Shutter::Draw::DrawingTool, first steps

### PR DESCRIPTION
**Pull request by ruzhnikov**
I moved the creation of uimanager to a separate module `Shutter::Draw::UIManager` and added DrawingTool's getters/setters that are needed for new functionality. Also added the module `Shutter::Draw::Utils` that will accumulate functions that aren't tied to methods or attributes of DrawingTool module.
There's also the module `Shutter::Draw::Ellipse` which is not used yet, I kept it for the next steps.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Thanks!

```
*** GooCanvas2::CanvasPoints::new: passed too many parameters (expected 2, got 3); ignoring excess at /home/somebody/shutter/share/shutter/resources/modules/Shutter/Draw/Utils.pm line 36.
        Shutter::Draw::Utils::points_to_canvas_points(126.690765380859, 169.557586669922, 237.476745605469, 271.231323242188) called at /home/somebody/shutter/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 4915
        Shutter::Draw::DrawingTool::handle_embedded(Shutter::Draw::DrawingTool=HASH(0x56420f8e3650), "update", GooCanvas2::CanvasRect=HASH(0x564210be02d8)) called at /home/somebody/shutter/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 2272
        Shutter::Draw::DrawingTool::event_item_on_motion_notify(Shutter::Draw::DrawingTool=HASH(0x56420f8e3650), GooCanvas2::CanvasRect=HASH(0x564210be0b30), GooCanvas2::CanvasRect=HASH(0x564210be0b30), Gtk3::Gdk::EventMotion=SCALAR(0x56420fece968)) called at /home/somebody/shutter/share/shutter/resources/modules/Shutter/Draw/DrawingTool.pm line 1839
```

When I'm trying to draw an arrow

Can you keep track somewhere of which new dependencies you're adding? So far it's Moo, strictures, anything else?

**Comment by ruzhnikov** [comment]
> GooCanvas2::CanvasPoints::new: passed too many parameters

Ok, I've found the problem, will fix soon.

> Can you keep track somewhere of which new dependencies you're adding?

Yes, it's a good idea. Right now I can't tell you what it would be because Shutter has a little unconventional structure for a perl project. I need to research.
What about new packages in the project, yes, it's `Moo` and `strictures`. I use `Test::MockModule` as well, but it's used only in tests and doesn't affect the main code of the project.

**Comment by DarthGandalf** [comment]
> Right now I can't tell you what it would be because Shutter has a little unconventional structure for a perl project

No problem! This is really just to update list of dependencies on the website when new version is ready. So that distro maintainers know how to package Shutter.

Also, welcome :)

**Comment by Photon89** [comment]
Welcome from me as well! :)

**Comment by vadi2** [comment]
Likewise :)

**Comment by ruzhnikov** [comment]
I've fixed the wrong working `points_to_canvas_points` function

**Comment by ruzhnikov** [comment]
I have also removed using `strictures` because it makes almost all warnings fatal. It can lead to the crash of the application in unexpected situation, and I suppose it couldn't be good for users of the program.

**Comment by ruzhnikov** [comment]
I have also added `cpanfile` for describing all dependencies of the project. I could miss something in the file, it might be appended later.

**Comment by DarthGandalf** [comment]
Is it ready to be merged yet?

**Comment by ruzhnikov** [comment]
> Is it ready to be merged yet?

Yes, it's ready

**Comment by DarthGandalf** [comment]
I thought you'd merge it

**Pull request merged**
