### PR TITLE
Applied changes by nicomen to prevent  "VAR will not stay shared" messages

### LINKED ISSUE #338: Should we stop using Carp::Always by default in the release version to reduce "noise"?
Shutter has a --debug option, maybe we should use Carp::Always only if it is passed to reduce the amount of output during regular usage?

### PR DESCRIPTION
**Pull request by Photon89**
See https://github.com/shutter-project/shutter/issues/703#issuecomment-2445587473 

Should close #338.

Thanks @nicomen!

### CODE REVIEW

**Review by nicomen — COMMENTED** [review]
I don't think this is a good fix. It was just a test to see if the theory was correct. The various "shared variables" should be passed in as parameters were fitting in the various functions.

Also there are a few more shared variable errors in the modules.

I would wait to merge this and see if I can make a slightly nicer fix.

**Comment by Photon89** [comment]
Sure, shall we close this PR then?

**Comment by nicomen** [comment]
Yes, please. I'll send a less destructive PR shortly.

**Comment by nicomen** [comment]
So, I went thru the code variable by variable trying to see which ones had to be global, and which one didn't. That took way too long and I didn't finish. But the result is that most variables need to global the way the code is written, so this patch is not THAT bad after all. Oh well.

**Comment by Photon89** [comment]
Thanks for taking so much time to deal with it!

**Comment by nicomen** [comment]
It's baffling that this has ever worked if it always was like that. Perhaps there is something I'm not getting. But oh well. Probably some more intelligent persons than me know some best practices in how to keep around state variables and such in a cleaner fashion when doing GUI programming.

**Comment by DarthGandalf** [comment]
It was different during Gtk2 times. Slightly different.

I made it like this during migration to Gtk3, because I don't know any better. I only made it work without caring too much about code quality, which was not the best already...

**Comment by nicomen** [comment]
Aha, that makes much more sense! Should probably have looked at the history :-) Thanks for getting the opprtunity to help. I found a new tool that I can use :-)

**Comment by Photon89** [comment]
So, should we merge this PR?

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
