### PR TITLE
Remove dysfunctional upload plugins, see #528

### LINKED ISSUE #323: Toile-libre upload broken
#### Brief summary of issue

upload to toile-libre gives back blank results
#### Steps to reproduce the issue

1. Take a screenshot
2. click on the option to upload it
3. choose toile-libre as a server

#### Error output
all links are blank (null)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
shutter 0.95 installed through linux-uprising ppa on ubuntu 20.04, kernel 5.4.0-66-generic

### LINKED ISSUE #528: We should probably tidy up broken upload plugins
#### Brief summary of issue

Several upload plugins are currently broken:

1.  Dropbox, requires a complete rewrite due to an API change, already broken for over five years: https://github.com/shutter-project/shutter/issues/228
2. Toilelibre, the service seems to be offline permanently: https://github.com/shutter-project/shutter/issues/323
3. Vgy.me, is currently dysfunctional, possibly it can be fixed though

#### Steps to reproduce the issue

1.  Try uploading with any of the upload services
2.  Observe that it is broken 

#### Error output

Output for vgy.me upload:

```
Use of uninitialized value $ARGV[0] in exists at /usr/share/shutter/resources/system/upload_plugins/upload/vgyme.pm line 55.
	require vgyme.pm called at /usr/bin/shutter line 10347
	eval {...} called at /usr/bin/shutter line 10345
	Shutter::App::dlg_upload("[17] - Auswahl_2022_12_16_05_54_18.png") called at /usr/bin/shutter line 6578
	Shutter::App::fct_upload(Gtk3::MenuToolButton=HASH(0x561217ab1bd0)) called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x5612160a63a8)) called at /usr/bin/shutter line 10943
Argument "Error POSTing https://vgy.me/upl..." isn't numeric in numeric ge (>=) at /usr/share/perl5/vendor_perl/HTTP/Status.pm line 151.
	HTTP::Status::is_success("Error POSTing https://vgy.me/upload.php: Not Found at /usr/sh"...) called at /usr/bin/shutter line 10381
	Shutter::App::dlg_upload("[17] - Auswahl_2022_12_16_05_54_18.png") called at /usr/bin/shutter line 6578
	Shutter::App::fct_upload(Gtk3::MenuToolButton=HASH(0x561217ab1bd0)) called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x5612160a63a8)) called at /usr/bin/shutter line 10943

```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

We should probably remove Dropbox and Toilelibre and see whether Vgy.me can be fixed with small effort.

### PR DESCRIPTION
**Pull request by Photon89**

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]

**Comment by DarthGandalf** [comment]
Does this also remove the need for any dependency?

**Comment by Photon89** [comment]
I don't think so, Imgur and Gyazo are still there and cover both authorized, OAuth and anonymous upload.

**Comment by Photon89** [comment]
On a second thought, `WWW::Mechanize` seems to be only used in vgyme and ToileLibre, so we could drop it. And  `Net::OAuth` seems to be only required by Dropbox, though Imgur also supports OAuth upload, it doesn't seem to load this module.

But please double check!

**Comment by Photon89** [comment]
@DarthGandalf Any further thoughts on this?

**Pull request merged**
