### PR TITLE
Fix for #453

### LINKED ISSUE #453: Shutter does not load profiles
#### Brief summary of issue
Shutter does not load profiles

$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

Linux asus1 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Steps to reproduce the issue

1. 
2. 
3. 

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-CRITICAL **: Source ID 807 was not found when attempting to remove it at /usr/bin/shutter line 6906.
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 6904.
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011Shutter::App::fct_show_status_message(1, "Settings saved successfully!") called at /usr/bin/shutter line 4611
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011Shutter::App::fct_save_settings(undef) called at /usr/bin/shutter line 3184
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011Shutter::App::__ANON__() called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x5591d87005b8)) called at /usr/bin/shutter line 10943
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: fct_update_tray_menu was called by Wnck::Screen=HASH(0x5591d86fe7c8)
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: message repeated 4 times: [ fct_update_tray_menu was called by Wnck::Screen=HASH(0x5591d86fe7c8)]
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: 3, 109879391 was emitted by widget Gtk3::StatusIcon=HASH(0x5591d8aa5c48)
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: quit was emitted by widget Gtk3::ImageMenuItem=HASH(0x5591d8955a88)
Feb  9 15:30:30 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed during global destruction.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]:  at /usr/bin/shutter line 0.
Feb  9 15:30:31 asus1 org.mate.panel.applet.MintMenuAppletFactory[99440]: #011eval {...} called at /usr/bin/shutter line 0
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: Subroutine Pango::Layout::set_text redefined at /usr/share/perl5/Gtk3.pm line 2260.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011require Gtk3.pm called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Shutter::App::BEGIN() called at /usr/share/perl5/Gtk3.pm line 2260
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011eval {...} called at /usr/share/perl5/Gtk3.pm line 2260
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: Subroutine Pango::Layout::set_markup redefined at /usr/share/perl5/Gtk3.pm line 2266.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011require Gtk3.pm called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Shutter::App::BEGIN() called at /usr/share/perl5/Gtk3.pm line 2266
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011eval {...} called at /usr/share/perl5/Gtk3.pm line 2266
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 110.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]:  at /usr/share/perl5/Gtk3.pm line 489.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Gtk3::import("Gtk3", "-init") called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Shutter::App::BEGIN() called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011eval {...} called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 110.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]:  at /usr/share/perl5/Gtk3.pm line 489.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Gtk3::import("Gtk3", "-init") called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011Shutter::App::BEGIN() called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: #011eval {...} called at /usr/bin/shutter line 72
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100787]: GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 110.
Feb  9 15:30:42 asus1 org.mate.panel.applet.MintMenuAppletFactory[100

### PR DESCRIPTION
**Pull request by Photon89**
We were hit by https://stackoverflow.com/questions/61765706/perl-sort-corrupts-bsd-glob-results

### CODE REVIEW

**Comment by Photon89** [comment]
For some reason all profiles are shown as active when the menu entries are created, which seems similar to https://stackoverflow.com/questions/3394919/gtkradiobutton-set-active-and-deactive But I don't yet understand the root of the problem...

**Comment by DarthGandalf** [comment]
> But I don't yet understand the root of the problem...

From your description it looks like they are assigned to different groups. And each of them is active in its own group

**Comment by Photon89** [comment]
Maybe it does not interpret the `$group` argument correctly in https://github.com/Photon89/shutter/blob/532a02954964951258f322ae8f3716931a3e7110/bin/shutter#L8772 It should actually have two arguments according to documentation in https://docs.gtk.org/gtk3/ctor.RadioMenuItem.new_with_label.html and also according to the working demo in https://github.com/dave-theunsub/gtk3-perl-demos/blob/9b521bc03c7a266819d3e5e3f64df590092dccf4/menus.pl#L124 But if I remove the last argument, I get a segmentation fault with

`undefined value for mandatory argument 'label' encountered at /usr/share/perl5/vendor_perl/Gtk3.pm line 1533.`

while with three arguments it works (besides of all entries being marked as active.

**Comment by DarthGandalf** [comment]
That example has `$group = $menuitem->get_group;` unlike how we set $group

**Comment by Photon89** [comment]
I tried to change it to the way it is defined in the example, but it doesn't have any effect.

**Comment by Photon89** [comment]
So I am still stuck with this... I tried to make it work with two arguments, as it is stated in the docs, but I get the output

```


$profile: Bla



$group: ARRAY(0x55798aff69f8)

undefined value for mandatory argument 'label' encountered at /usr/share/perl5/vendor_perl/Gtk3.pm line 1533.
	Gtk3::__ANON__(ARRAY(0x55798aff69f8), "Bla") called at /usr/sbin/shutter line 8774
	Shutter::App::fct_ret_profile_menu(Gtk3::ComboBoxText=HASH(0x55798f52e7b8), ARRAY(0x55798cf91140)) called at /usr/sbin/shutter line 7115
	Shutter::App::fct_update_profile_selectors(Gtk3::ComboBoxText=HASH(0x55798f52e7b8), ARRAY(0x55798cf91140)) called at /usr/sbin/shutter line 2705
	Shutter::App::STARTUP(Shutter::App=HASH(0x55798efb2a48)) called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55798efb2a48)) called at /usr/sbin/shutter line 10955

```

from 

```
[...]
		my $group   = [];
		my $counter = 0;
		foreach my $profile (@{$current_profiles_ref}) {
			print "\n\n\$profile: $profile\n\n";
			print "\n\n\$group: $group\n\n";
			my $profile_item = Gtk3::RadioMenuItem::new_with_label($group, $profile);
[...]
```

The label argument (second argument in Gtk3::RadioMenuItem::new_with_label) is set to $profile which is printed as "Bla" but the output claims that it has an undefined value...

**Comment by Photon89** [comment]
Oh my gosh, I am stupid...

**Comment by Photon89** [comment]
Ready for merging!

**Pull request merged**
