### PR TITLE
Add a very crude wayland support

### PR DESCRIPTION
**Pull request by DarthGandalf**
Ref #187

### CODE REVIEW

**Comment by Photon89** [comment]
I tested it in a VM running Ubuntu Gnome 21.04. When I click the "Capture Desktop" button, I get a window asking for permission and showing a preview image of the desktop. When I allow to share the screen, nothing further happens, Shutter stays minimized and when showing the window, no screenshot is there.

**Comment by DarthGandalf** [comment]
Confirmed on gnome vm.

```
*** unhandled exception in callback:
***   org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Request” on object at path /org/freedesktop/portal/desktop/request/1_690/shutter0386827569565369
```

**Comment by DarthGandalf** [comment]
Fixed.

**Comment by Photon89** [comment]
Confirmed, desktop capture works now! Great news! :smiley:

**Pull request merged**
