### PR TITLE
Gtk3

### PR DESCRIPTION
**Pull request by DarthGandalf**
The biggest blockers:
* ~~Gtk2::ImageView doesn't have analog in Gtk3.~~ Working with author of Gtk2::ImageView who also made a partial port of it to Gtk3 to add missing features. It's used in 3 places:
  * showing the screenshot in the tab, zoomed
  * while selecting the rectangle of the area to take screenshot of
  * draw tool
  * Update: Gtk3::ImageView is now done and used here.
* ~~I can't figure out how to access subwindows, because `->XWINDOW` is missing. The same function is needed for capturing context menus.~~ It's `->get_xid` now
* ~~I didn't yet try to fix the drawing. There is GooCanvas2, but I don't yet know how compatible it is with Goo::Canvas~~
* ~~Blurry preview window during Selection, blocked on [upstream bug of goocanvas2](https://gitlab.gnome.org/GNOME/goocanvas/-/merge_requests/9)~~ added a workaround

Other things are not done yet, but are doable with a bit of effort:
* ~~libunique needs porting to GtkApplication and Gio SimpleAction; I have a hello world app working~~
* ~~drag'n'drop shows some error in type, probably needs some massaging of GObject Introspection.~~
* and a couple of other issues mentioned in `TODO-GTK3.md`

In the current state it can take screenshot of the whole desktop, of a single window, can upload, and even fixes an encoding bug of the current release (desktop name was garbled).

### CODE REVIEW

**Comment by Photon89** [comment]
Regarding Gtk2::ImageView, this guy seems to have had the same problem and describes how he worked around it: https://martin.hoppenheit.info/blog/2014/image-scaling-with-gtk3-and-perl/ Looks like it is applicable at least for the preview in the screenshot tab.

**Comment by Photon89** [comment]
I created an issue, which outdated libs are blocking Shutter from entering the repos (for Arch Linux so far), to get some overview: https://github.com/shutter-project/shutter/issues/285

**Comment by Photon89** [comment]
I thought I'd try to play around with the GooCanvas thingy and tried to run the latest commit from the gtk3 branch, but get

`Can't locate object method "window" via package "Gtk3::MessageDialog" at bin/shutter line 7957.`

Is this expected or is something messed up on my machine? I'm using this as `Gtk3`: https://www.archlinux.org/packages/community/any/perl-gtk3/

When removing the `!$plugin_dialog->window` check, it shows a tray icon but not the main window and the tray icon is dysfunctional.

**Comment by DarthGandalf** [comment]
That's one of differences between perl-gtk2 and perl-gtk3. I kept changing it to `get_window` where I encountered this. But that codepath was never executed for me, because plugins were cached in settings xml already (by the gtk2 version), because I run one or another to understand what a particular button should do, if it didn't work in gtk3.

Fixed.

**Comment by Photon89** [comment]
Launches and looks great, thanks! :)

**Comment by vadi2** [comment]
How would I test this? Checkout and then run what?

**Comment by Photon89** [comment]
Just run bin/shutter from the main folder of the checked out repo.

**Comment by DarthGandalf** [comment]
New release doesn't need to wait for this branch, btw.

**Comment by Photon89** [comment]
Ok, then I will prepare the release asap!

**Comment by DarthGandalf** [comment]
Gscan2pdf had the same problem when migrating to Gtk3, therefore `Gscan2pdf::ImageView` mostly fits here, and is mostly compatible with our code.

**Comment by Photon89** [comment]
Cool, selection and desktop mode work very nicely! One minor, rather cosmetic, thing, which you are probably aware of already: The little zoomed preview window is shown in the desktop mode and also after the selection screen in the selection mode.

**Comment by DarthGandalf** [comment]
Zoomed preview window has several cosmetic problems which I didn't fix yet, but not disappearing is not one of those which I saw. Can you show a screenshot?

**Comment by DarthGandalf** [comment]
...and logs

**Comment by Photon89** [comment]
Wifi is very bad here and I'd need to make a little screencast. But here are logs for a desktop capture:

```
full was emitted by widget Gtk3::MenuToolButton=HASH(0x560df1cccf48)
3 Ns used in wild-card
Searching for files with pattern: (?^u:\$name_(\d\d\d)\.png)
Searching for files with pattern: (?^u:.{1,}_(\d\d\d)\.png)
Comparing Auswahl_002.png
002 is currently greatest value...
Comparing Auswahl_001.png
Comparing equal time hypersurfaces sketch.png
Comparing Skype Preview_003.png
003 is currently greatest value...
Comparing Auswahl_004.png
004 is currently greatest value...
Comparing Workspace 1_006.png
006 is currently greatest value...
Comparing Workspace 1_005.png
Comparing Auswahl_104.png
104 is currently greatest value...
Comparing Auswahl_097.png
Comparing Auswahl_116.png
116 is currently greatest value...
Comparing Auswahl_125.png
125 is currently greatest value...
Comparing Auswahl_018.png
Comparing gnuplot.png
Comparing Auswahl_023.png
Comparing Auswahl_009.png
Comparing Auswahl_124.png
Comparing Workspace 1_017.png
Comparing Auswahl_041.png
Comparing Auswahl_138.png
138 is currently greatest value...
Comparing Auswahl_127.png
Comparing Auswahl_091.png
Comparing Auswahl_149.png
149 is currently greatest value...
Comparing Auswahl_042.png
Comparing Auswahl_022.png
Comparing Auswahl_117.png
Comparing Auswahl_126.png
Comparing Auswahl_040.png
Comparing Auswahl_093.png
Comparing Auswahl_039.png
Comparing Auswahl_098.png
Comparing Auswahl_137.png
Comparing Auswahl_139.png
Comparing Auswahl_107.png
Comparing Auswahl_130.png
Comparing Auswahl_147.png
Comparing Auswahl_129.png
Comparing Auswahl_123.png
Comparing Auswahl_128.png
Comparing Auswahl_100.png
Comparing Auswahl_111.png
Comparing Auswahl_048.png
Comparing Auswahl_103.png
Comparing Auswahl_112.png
Comparing Auswahl_109.png
Comparing Auswahl_121.png
Comparing Auswahl_115.png
Comparing Auswahl_118.png
Comparing Auswahl_120.png
Comparing Auswahl_119.png
Comparing Auswahl_131.png
Comparing Auswahl_142.png
Comparing Auswahl_122.png
Comparing Auswahl_031.png
Comparing Auswahl_135.png
Comparing Auswahl_134.png
Comparing Auswahl_092.png
Comparing diesel.png
Comparing Auswahl_136.png
Comparing Auswahl_099.png
Comparing Auswahl_036.png
Comparing Auswahl_106.png
Comparing Auswahl_108.png
Comparing Auswahl_095.png
Comparing Auswahl_141.png
Comparing Auswahl_094.png
Comparing Auswahl_113.png
Comparing Auswahl_132.png
Comparing Auswahl_133.png
Comparing Auswahl_096.png
Comparing Auswahl_114.png
Comparing Auswahl_110.png
Comparing Auswahl_102.png
Comparing Auswahl_105.png
Comparing Auswahl_101.png
Comparing Auswahl_146.png
Comparing Auswahl_140.png
Comparing Auswahl_144.png
Comparing Auswahl_145.png
Comparing Auswahl_143.png
Comparing Auswahl_148.png
Comparing Diesel_Engine_(4_cycle_running).gif
Parsing wildcards for /home/photon/Bilder/$name_150.png
Parsed $width and $height: /home/photon/Bilder/$name_150.png
Parsed $profile: /home/photon/Bilder/$name_150.png
Parsed $name: /home/photon/Bilder/Workspace 1_150.png
New uri after exists check: /home/photon/Bilder/Workspace 1_150.png
Trying to save file to /home/photon/Bilder/Workspace 1_150.png
Saving file /home/photon/Bilder/Workspace 1_150.png, png, 9
Updating fileinfos for key: [1] - Workspace 1_150.png
GLib-GObject-WARNING **: value "0.000781" of type 'gfloat' is invalid or out of range for property 'zoom' of type 'gfloat' at /home/photon/shutter-git/shutter/share/shutter/resources/modules/Shutter/ImageView.pm line 463.
	Shutter::ImageView::_set_zoom(Shutter::ImageView=HASH(0x560df21032a8), 0.00078125) called at /home/photon/shutter-git/shutter/share/shutter/resources/modules/Shutter/ImageView.pm line 506
	Shutter::ImageView::_set_zoom_with_center(Shutter::ImageView=HASH(0x560df21032a8), 0.00078125, 640, 400) called at /home/photon/shutter-git/shutter/share/shutter/resources/modules/Shutter/ImageView.pm line 543
	Shutter::ImageView::zoom_to_box(Shutter::ImageView=HASH(0x560df21032a8), HASH(0x560df1e9af38)) called at /home/photon/shutter-git/shutter/share/shutter/resources/modules/Shutter/ImageView.pm line 526
	Shutter::ImageView::set_zoom_to_fit(Shutter::ImageView=HASH(0x560df21032a8), 1) called at /home/photon/shutter-git/shutter/share/shutter/resources/modules/Shutter/ImageView.pm line 229
	Shutter::ImageView::set_pixbuf(Shutter::ImageView=HASH(0x560df21032a8), Gtk3::Gdk::Pixbuf=HASH(0x560df2066168), 1) called at bin/shutter line 7272
	Shutter::App::fct_update_tab("[1] - Workspace 1_150.png", Gtk3::Gdk::Pixbuf=HASH(0x560df2066168), Glib::Object::_Unregistered::GLocalFile=HASH(0x560df21034d0)) called at bin/shutter line 4032
	Shutter::App::fct_integrate_screenshot_in_notebook(Glib::Object::_Unregistered::GLocalFile=HASH(0x560df21034d0), Gtk3::Gdk::Pixbuf=HASH(0x560df2066168), Shutter::Screenshot::Workspace=HASH(0x560ded714f30)) called at bin/shutter line 6461
	Shutter::App::fct_take_screenshot(Gtk3::MenuToolButton=HASH(0x560df1cccf48), "full", undef, undef) called at bin/shutter line 3026
	Shutter::App::__ANON__() called at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x560df0f6b4b8)) called at bin/shutter line 10808
screenshot successfully saved to /home/photon/Bilder/Workspace 1_150.png!
GLib-CRITICAL **: Source ID 31 was not found when attempting to remove it at bin/shutter line 6924.
	Shutter::App::fct_show_status_message(1, "Workspace 1_150.png saved") called at bin/shutter line 6502
	Shutter::App::fct_take_screenshot(Gtk3::MenuToolButton=HASH(0x560df1cccf48), "full", undef, undef) called at bin/shutter line 3026
	Shutter::App::__ANON__() called at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x560df0f6b4b8)) called at bin/shutter line 10808
```

**Comment by DarthGandalf** [comment]
A screencast would help

**Comment by Photon89** [comment]
I made a low framerate screencast:

[simplescreenrecorder-2020-07-13_14.34.29.mp4.zip](https://github.com/shutter-project/shutter/files/4912442/simplescreenrecorder-2020-07-13_14.34.29.mp4.zip)

**Comment by DarthGandalf** [comment]
@Photon89 I don't understand what's going on in that video. Are you referring to the white square on top left? It doesn't look like the zoom preview.

**Comment by Photon89** [comment]
Yes, exactly! Well, possibly it is something else, but it appears for a second when the gtk3 branch Shutter takes a screenshot and does not appear .otherwise.

**Comment by vrkansagara** [comment]
is this ready to publish this draft ?

**Comment by DarthGandalf** [comment]
@vrkansagara there are still several issues, but you can try it. Not everything works yet. I had to patch some dependencies (e.g. goocanvas-2), so sidetracked on pushing these patches upstream. I don't remember what's the current state of the PR is - whether it makes use of the patches yet or not, because I patched them locally and might have pushed the PR.

For now it looks like that [this will have to wait for goocanvas-3](https://gitlab.gnome.org/GNOME/goocanvas/-/merge_requests/9) release, unless we figure out how to avoid the need to patch it, or e.g. remove that dep completely.

**Comment by vadi2** [comment]
Force pushing makes it hard to review - could we do without it?

**Comment by DarthGandalf** [comment]
I only combined two last commits into one, and improved the commit message
there

чт, 18 февр. 2021 г., 04:37 Vadim Peretokin <notifications@github.com>:

**Comment by vadi2** [comment]
It looks like we're pretty dependant on a project that is not actively maintained, this is a problem. :(

**Comment by DarthGandalf** [comment]
Nah, that particular problem is worked around already, I pushed the commit
here and updated the PR description

сб, 13 мар. 2021 г., 08:04 Vadim Peretokin ***@***.***>:

**Comment by DarthGandalf** [comment]
But you are right that after this migration is done, we may need to look
for alternatives

сб, 13 мар. 2021 г., 08:04 Vadim Peretokin ***@***.***>:

**Comment by DarthGandalf** [comment]
Alright, I did what I could here. The most broken things remaining:
* support for multiple displays: I don't know whether it works - I might have broken it, if it ever worked, but I cannot test
* on hidpi screens (with e.g. `GDK_DPI_SCALE=0.5 GDK_SCALE=2` in environment) subwindow capture and menu capture take wrong part of the screen; I must have used wrong formula somewhere, but I don't know how to fix this

I'll need some help with those. And I don't know whether these issues are important enough to delay the release vs not having shutter in repos at all...

Also a few minor things:
* draw tool: I just removed the rulers on top and left of the image because I couldn't find any replacement for them
* cursor in the selector behaves slightly differently near the edges of the selection. Probably could be fixed, but it's not that big deal
* in one of my tests the execution via `ssh -X` didn't work well, I don't know whether it's still a problem, or how to fix it

**Pull request merged**
