### PR TITLE
Generated .mo files manually + generating script

### PR DESCRIPTION
**Pull request by Photon89**
Since we have no translation service set up so far, I have generated the .mo files using a bash script for now. Also added the script itself, don't know if it belongs here though.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
I think such generated binary files don't belong to the source repo at all. They should be generated during packaging/build time using such script.

**Comment by Photon89** [comment]
I will try to look into how to write a Makefile, I guess. :smiley:

**Comment by vadi2** [comment]
What about something more modern like Meson? It's popular with gnome projects, I think.

**Comment by Photon89** [comment]
I don't have any opinion since I never used any of these build systems from a developer perspective. From a packager perspective, a simple Makefile has the advantage that no additional make dependencies are required (make is included in meta packages like build-essential on Debian based distros or base-devel on Arch based distros).

**Comment by DarthGandalf** [comment]
Even `po2mo.sh` added here would work as the "build system". Though because it's so unusual build system, it probably should be mentioned in readme. Or write a Makefile which simply calls that script.

But I don't mind some other build system either, if you see some profit in using it.

**Comment by Photon89** [comment]
I gave it a try writing a Makefile. If called without further options, it will install into /usr as prefix, calling like

make prefix=./pkg install

will install into ./pkg for example. Also removed the old ubuntu-mono icons which aren't used anyway, I guess (right? :smile: ), and update-notifier-shutter, which informed users that the name is Shutter and not GScrot ten years ago.

**Comment by DarthGandalf** [comment]
Usually the default is /usr/local
/usr is for packages installed by the package manager


14.06.2020 18:59, Photon89 пишет:

**Comment by Photon89** [comment]
Didn't know that, thanks for the hint!

**Comment by DarthGandalf** [comment]
```
$ make prefix=./pkg install                                                                                                                                                                                                                                                       
install -Dm755 bin/shutter ./pkg/bin/shutter                                                                                                                                                                                                                                      
cp -r share/ ./pkg/

$ find . -name '*mo'                                                

$ LC_ALL=C bash -ex ./po2mo.sh
+++ dirname ./po2mo.sh
++ cd .
++ pwd -P
+ SCRIPTPATH=/home/somebody/shutter
+ POPATH=/home/somebody/shutter/share/shutter/resources/po
+ MOPATH=/home/somebody/shutter/share/locale
+ for POFOLDER in $POPATH/*
+ for POFILE in ${POFOLDER}/*.po
++ cut -d. -f1
+++ basename /home/somebody/shutter/share/shutter/resources/po/shutter/af.po
++ echo af.po
+ LOCALE=af
+ '[' '!' -d /home/somebody/shutter/share/locale/af ']'
+ mkdir /home/somebody/shutter/share/locale/af
mkdir: cannot create directory '/home/somebody/shutter/share/locale/af': No such file or directory
```

**Comment by Photon89** [comment]
Thanks for testing!

First problem: You should run make first to generate the .mo files, then make install to put the files into the prefix.

Second problem: Fixed!

edit: Sorry, not fixed, I will have a look.

**Comment by Photon89** [comment]
Should work now.

**Comment by vadi2** [comment]
Yep fair, simple makefile is best for this.

**Comment by DarthGandalf** [comment]
Please add `all` as a dependency to `install`, so that `make install` is enough.

I haven't tested uninstall, because it's a job of package manager.

**Review by DarthGandalf — APPROVED** [review]

**Pull request merged**
